# Form implementation generated from reading ui file 'architectai.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1216, 831)
        MainWindow.setStyleSheet("\n"
"/* ── Global ── */\n"
"QMainWindow, QWidget#centralWidget {\n"
"    background-color: #0d0f12;\n"
"    color: #c8d4e8;\n"
"    font-family: \"Courier New\", monospace;\n"
"    font-size: 11px;\n"
"}\n"
"\n"
"/* --- Tree Widget Arrows --- */\n"
"QTreeWidget#fileTree::branch:has-children:closed {\n"
"    border-image: url(:/assets/right_arrow.svg);\n"
"    image: none;\n"
"}\n"
"\n"
"QTreeWidget#fileTree::branch:has-children:open {\n"
"    border-image: url(:/assets/down_arrow.svg);\n"
"    image: none;\n"
"}\n"
"\n"
"QTreeWidget#fileTree::branch:!has-children {\n"
"    border-image: none;\n"
"    image: none;\n"
"}\n"
"\n"
"/* ── Menu Bar ── */\n"
"QMenuBar {\n"
"    background-color: #12151a;\n"
"    color: #5a6a82;\n"
"    border-bottom: 1px solid #252c3a;\n"
"    font-size: 11px;\n"
"    padding: 2px 4px;\n"
"}\n"
"QMenuBar::item:selected {\n"
"    background-color: #1e2330;\n"
"    color: #c8d4e8;\n"
"    border-radius: 4px;\n"
"}\n"
"QMenu {\n"
"    background-color: #12151a;\n"
"    border: 1px solid #252c3a;\n"
"    color: #c8d4e8;\n"
"}\n"
"QMenu::item:selected {\n"
"    background-color: #1e2330;\n"
"}\n"
"\n"
"/* ── Status Bar ── */\n"
"QStatusBar {\n"
"    background-color: #1d4ed8;\n"
"    color: rgba(255,255,255,0.8);\n"
"    font-size: 10px;\n"
"    min-height: 22px;\n"
"}\n"
"QStatusBar::item { border: none; }\n"
"\n"
"/* ── Splitter ── */\n"
"QSplitter::handle {\n"
"    background-color: #252c3a;\n"
"    width: 1px;\n"
"    height: 1px;\n"
"}\n"
"\n"
"/* ── Scroll Bars ── */\n"
"QScrollBar:vertical {\n"
"    background: transparent;\n"
"    width: 5px;\n"
"    margin: 0;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: #2e3849;\n"
"    border-radius: 2px;\n"
"    min-height: 20px;\n"
"}\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical { height: 0; }\n"
"QScrollBar:horizontal {\n"
"    background: transparent;\n"
"    height: 5px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: #2e3849;\n"
"    border-radius: 2px;\n"
"}\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal { width: 0; }\n"
"\n"
"/* ── Generic Panels ── */\n"
"QFrame#sidebarFrame {\n"
"    background-color: #12151a;\n"
"    border-right: 1px solid #252c3a;\n"
"}\n"
"QFrame#promptFrame {\n"
"    background-color: #12151a;\n"
"    border-bottom: 1px solid #252c3a;\n"
"}\n"
"QFrame#rightPanelFrame {\n"
"    background-color: #0d0f12;\n"
"    border-left: 1px solid #252c3a;\n"
"}\n"
"QFrame#dockerFrame {\n"
"    background-color: #12151a;\n"
"    border-top: 1px solid #252c3a;\n"
"}\n"
"\n"
"/* ── Section Labels ── */\n"
"QLabel#sectionLabel {\n"
"    background-color: #12151a;\n"
"    color: #5a6a82;\n"
"    font-size: 10px;\n"
"    font-weight: bold;\n"
"    letter-spacing: 2px;\n"
"    padding: 6px 14px;\n"
"    border-bottom: 1px solid #252c3a;\n"
"}\n"
"QLabel#panelLabel {\n"
"    color: #5a6a82;\n"
"    font-size: 10px;\n"
"    font-weight: bold;\n"
"    letter-spacing: 2px;\n"
"}\n"
"QLabel#promptLabel {\n"
"    color: #3b82f6;\n"
"    font-size: 10px;\n"
"    font-weight: bold;\n"
"    letter-spacing: 2px;\n"
"}\n"
"\n"
"/* ── Prompt TextEdit ── */\n"
"QTextEdit#promptEdit {\n"
"    background-color: #181c23;\n"
"    border: 1px solid #2e3849;\n"
"    border-radius: 6px;\n"
"    color: #e8f0fc;\n"
"    font-family: \"Courier New\", monospace;\n"
"    font-size: 12px;\n"
"    padding: 6px 10px;\n"
"    selection-background-color: #1e3a5f;\n"
"}\n"
"QTextEdit#promptEdit:focus {\n"
"    border: 1px solid #3b82f6;\n"
"}\n"
"\n"
"/* ── Log Output ── */\n"
"QPlainTextEdit#logOutput {\n"
"    background-color: #0d0f12;\n"
"    border: none;\n"
"    color: #c8d4e8;\n"
"    font-family: \"Courier New\", monospace;\n"
"    font-size: 11px;\n"
"    padding: 8px;\n"
"    selection-background-color: #1e3a5f;\n"
"}\n"
"\n"
"/* ── Tab Widget ── */\n"
"QTabWidget#logTabs::pane {\n"
"    border: none;\n"
"    background-color: #0d0f12;\n"
"}\n"
"QTabWidget#logTabs > QTabBar {\n"
"    background-color: #12151a;\n"
"    qproperty-drawBase: 0;\n"
"}\n"
"QTabBar::tab {\n"
"    background-color: transparent;\n"
"    color: #5a6a82;\n"
"    border: 1px solid transparent;\n"
"    border-bottom: none;\n"
"    border-radius: 5px 5px 0 0;\n"
"    padding: 5px 14px;\n"
"    margin-right: 2px;\n"
"    font-size: 11px;\n"
"}\n"
"QTabBar::tab:selected {\n"
"    background-color: #0d0f12;\n"
"    color: #e8f0fc;\n"
"    border-color: #252c3a;\n"
"}\n"
"QTabBar::tab:hover:!selected {\n"
"    background-color: #181c23;\n"
"    color: #c8d4e8;\n"
"}\n"
"\n"
"/* ── Agent List ── */\n"
"QListWidget#agentList {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    outline: none;\n"
"    padding: 6px;\n"
"}\n"
"QListWidget#agentList::item {\n"
"    background-color: transparent;\n"
"    border: 1px solid transparent;\n"
"    border-radius: 6px;\n"
"    color: #c8d4e8;\n"
"    padding: 6px 8px;\n"
"    margin-bottom: 2px;\n"
"    min-height: 36px;\n"
"}\n"
"QListWidget#agentList::item:hover {\n"
"    background-color: #181c23;\n"
"}\n"
"QListWidget#agentList::item:selected {\n"
"    background-color: #1e2330;\n"
"    border-color: #2e3849;\n"
"    color: #e8f0fc;\n"
"}\n"
"\n"
"/* ── File Tree ── */\n"
"QTreeWidget#fileTree {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: #c8d4e8;\n"
"    font-size: 11px;\n"
"    outline: none;\n"
"}\n"
"QTreeWidget#fileTree::item {\n"
"    padding: 2px 4px;\n"
"    border-radius: 4px;\n"
"}\n"
"QTreeWidget#fileTree::item:hover {\n"
"    background-color: #181c23;\n"
"}\n"
"QTreeWidget#fileTree::item:selected {\n"
"    background-color: #1e2330;\n"
"    color: #e8f0fc;\n"
"}\n"
"QTreeWidget#fileTree::branch {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"/* ── Docker Table ── */\n"
"QTableWidget#dockerTable {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: #c8d4e8;\n"
"    font-size: 11px;\n"
"    gridline-color: transparent;\n"
"    outline: none;\n"
"}\n"
"QTableWidget#dockerTable::item {\n"
"    padding: 4px 8px;\n"
"    border-radius: 4px;\n"
"    border-bottom: 1px solid #1e2330;\n"
"}\n"
"QTableWidget#dockerTable::item:selected {\n"
"    background-color: #1e2330;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #12151a;\n"
"    color: #5a6a82;\n"
"    border: none;\n"
"    border-bottom: 1px solid #252c3a;\n"
"    padding: 4px 8px;\n"
"    font-size: 10px;\n"
"    letter-spacing: 1px;\n"
"}\n"
"\n"
"/* ── Progress Bar ── */\n"
"QProgressBar#pipelineProgress {\n"
"    background-color: #181c23;\n"
"    border: 1px solid #252c3a;\n"
"    border-radius: 3px;\n"
"    height: 5px;\n"
"    text-align: center;\n"
"    color: transparent;\n"
"}\n"
"QProgressBar#pipelineProgress::chunk {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #3b82f6, stop:1 #06b6d4);\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"/* ── Run Button ── */\n"
"QPushButton#runButton {\n"
"    background-color: #3b82f6;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    font-family: \"Courier New\", monospace;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    letter-spacing: 2px;\n"
"    padding: 9px 16px;\n"
"}\n"
"QPushButton#runButton:hover {\n"
"    background-color: #1d4ed8;\n"
"}\n"
"QPushButton#runButton:pressed {\n"
"    background-color: #1e40af;\n"
"}\n"
"\n"
"/* ── Stop Button ── */\n"
"QPushButton#stopButton {\n"
"    background-color: transparent;\n"
"    color: #5a6a82;\n"
"    border: 1px solid #252c3a;\n"
"    border-radius: 6px;\n"
"    font-size: 11px;\n"
"    padding: 7px 14px;\n"
"}\n"
"QPushButton#stopButton:hover {\n"
"    background-color: #1e2330;\n"
"    color: #ef4444;\n"
"    border-color: #ef4444;\n"
"}\n"
"\n"
"/* --- LAUNCH BUTTON STATES (Matches RUN) --- */\n"
"QPushButton#launchButton {\n"
"    background-color: #3b82f6; color: #ffffff; border: none; border-radius: 6px;\n"
"    font-family: \"Courier New\", monospace; font-size: 12px; font-weight: bold; \n"
"    letter-spacing: 2px; padding: 9px 16px; margin-top: 2px;\n"
"}\n"
"QPushButton#launchButton:hover { background-color: #1d4ed8; }\n"
"QPushButton#launchButton:pressed { background-color: #1e40af; }\n"
"QPushButton#launchButton:disabled {\n"
"    background-color: transparent; \n"
"    color: #5a6a82; \n"
"    border: 1px solid #252c3a;\n"
"    border-radius: 6px;   /* Added back */\n"
"    padding: 9px 16px;    /* Added back */\n"
"}\n"
"\n"
"/* --- DESTROY BUTTON STATES (Matches STOP) --- */\n"
"QPushButton#stopPrototypeButton {\n"
"    background-color: #ef4444; color: #ffffff; border: none; border-radius: 6px;\n"
"    font-family: \"Courier New\", monospace; font-size: 11px; font-weight: bold; \n"
"    padding: 7px 14px; letter-spacing: 1px; margin-top: 2px;\n"
"}\n"
"QPushButton#stopPrototypeButton:hover { background-color: #dc2626; }\n"
"QPushButton#stopPrototypeButton:pressed { background-color: #b91c1c; }\n"
"QPushButton#stopPrototypeButton:disabled {\n"
"    background-color: transparent; \n"
"    color: #5a6a82; \n"
"    border: 1px solid #252c3a;\n"
"    border-radius: 6px;\n"
"    padding: 7px 14px;\n"
"}\n"
"/* ── Live badge label ── */\n"
"QLabel#liveBadge {\n"
"    background-color: #166534;\n"
"    color: #22c55e;\n"
"    border-radius: 3px;\n"
"    font-size: 9px;\n"
"    padding: 1px 6px;\n"
"    letter-spacing: 1px;\n"
"}\n"
"QLabel#autoscrollLabel {\n"
"    color: #5a6a82;\n"
"    font-size: 10px;\n"
"}\n"
"\n"
"/* ── Progress label ── */\n"
"QLabel#progressLabel {\n"
"    color: #5a6a82;\n"
"    font-size: 10px;\n"
"    letter-spacing: 1px;\n"
"}\n"
"QLabel#progressPct {\n"
"    color: #3b82f6;\n"
"    font-size: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* ── Table Corner Button Fix ── */\n"
"QTableCornerButton::section {\n"
"    background-color: #12151a;\n"
"    border: none;\n"
"}\n"
"\n"
"QListWidget#agentList {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    outline: none;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QListWidget#agentList::item {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    padding: 0px;\n"
"    margin-bottom: 2px;\n"
"    min-height: 36px;\n"
"}\n"
"\n"
"QListWidget#agentList::item:hover, \n"
"QListWidget#agentList::item:selected {\n"
"    background-color: transparent;\n"
"}\n"
"  \n"
"/* Add this to the MainWindow stylesheet in Qt Designer */\n"
"\n"
"/* --- RUN BUTTON STATES --- */\n"
"QPushButton#runButton {\n"
"    background-color: #3b82f6; color: #ffffff; border: none; border-radius: 6px;\n"
"    font-family: \"Courier New\", monospace; font-size: 12px; font-weight: bold; \n"
"    letter-spacing: 2px; padding: 9px 16px;\n"
"}\n"
"QPushButton#runButton:hover { background-color: #1d4ed8; }\n"
"QPushButton#runButton:pressed { background-color: #1e40af; }\n"
"QPushButton#runButton:disabled {\n"
"    background-color: transparent; \n"
"    color: #5a6a82; \n"
"    border: 1px solid #252c3a;\n"
"    border-radius: 6px;\n"
"    padding: 9px 16px;\n"
"}\n"
"/* --- STOP BUTTON STATES --- */\n"
"QPushButton#stopButton {\n"
"    background-color: #ef4444; color: #ffffff; border: none; border-radius: 6px;\n"
"    font-size: 11px; font-weight: bold; padding: 7px 14px; letter-spacing: 1px;\n"
"}\n"
"QPushButton#stopButton:hover { background-color: #dc2626; }\n"
"QPushButton#stopButton:pressed { background-color: #b91c1c; }\n"
"QPushButton#stopButton:disabled {\n"
"    background-color: transparent; \n"
"    color: #5a6a82; \n"
"    border: 1px solid #252c3a;\n"
"    border-radius: 6px;\n"
"    padding: 7px 14px;\n"
"}\n"
"")
        self.centralWidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.rootLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.rootLayout.setContentsMargins(0, 0, 0, 0)
        self.rootLayout.setSpacing(0)
        self.rootLayout.setObjectName("rootLayout")
        self.promptFrame = QtWidgets.QFrame(parent=self.centralWidget)
        self.promptFrame.setMaximumSize(QtCore.QSize(16777215, 80))
        self.promptFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.promptFrame.setProperty("fixedHeight", 76)
        self.promptFrame.setObjectName("promptFrame")
        self.promptLayout = QtWidgets.QHBoxLayout(self.promptFrame)
        self.promptLayout.setContentsMargins(14, 10, 14, 10)
        self.promptLayout.setSpacing(10)
        self.promptLayout.setObjectName("promptLayout")
        self.promptLabel = QtWidgets.QLabel(parent=self.promptFrame)
        self.promptLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignTop)
        self.promptLabel.setObjectName("promptLabel")
        self.promptLayout.addWidget(self.promptLabel)
        self.promptEdit = QtWidgets.QTextEdit(parent=self.promptFrame)
        self.promptEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.promptEdit.setAcceptRichText(False)
        self.promptEdit.setObjectName("promptEdit")
        self.promptLayout.addWidget(self.promptEdit)
        self.rootLayout.addWidget(self.promptFrame)
        self.mainSplitter = QtWidgets.QSplitter(parent=self.centralWidget)
        self.mainSplitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.mainSplitter.setChildrenCollapsible(False)
        self.mainSplitter.setObjectName("mainSplitter")
        self.sidebarFrame = QtWidgets.QFrame(parent=self.mainSplitter)
        self.sidebarFrame.setMaximumSize(QtCore.QSize(250, 16777215))
        self.sidebarFrame.setObjectName("sidebarFrame")
        self.sidebarLayout = QtWidgets.QVBoxLayout(self.sidebarFrame)
        self.sidebarLayout.setContentsMargins(0, 0, 0, 0)
        self.sidebarLayout.setSpacing(0)
        self.sidebarLayout.setObjectName("sidebarLayout")
        self.sectionLabel = QtWidgets.QLabel(parent=self.sidebarFrame)
        self.sectionLabel.setObjectName("sectionLabel")
        self.sidebarLayout.addWidget(self.sectionLabel)
        self.agentList = QtWidgets.QListWidget(parent=self.sidebarFrame)
        self.agentList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.agentList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.agentList.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.NoSelection)
        self.agentList.setObjectName("agentList")
        item = QtWidgets.QListWidgetItem()
        self.agentList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.agentList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.agentList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.agentList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.agentList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.agentList.addItem(item)
        self.sidebarLayout.addWidget(self.agentList)
        self.progressLayout = QtWidgets.QVBoxLayout()
        self.progressLayout.setContentsMargins(12, 6, 12, 4)
        self.progressLayout.setSpacing(5)
        self.progressLayout.setObjectName("progressLayout")
        self.progressLabelRow = QtWidgets.QHBoxLayout()
        self.progressLabelRow.setObjectName("progressLabelRow")
        self.progressLabel = QtWidgets.QLabel(parent=self.sidebarFrame)
        self.progressLabel.setObjectName("progressLabel")
        self.progressLabelRow.addWidget(self.progressLabel)
        spacerItem = QtWidgets.QSpacerItem(5, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.progressLabelRow.addItem(spacerItem)
        self.progressPct = QtWidgets.QLabel(parent=self.sidebarFrame)
        self.progressPct.setObjectName("progressPct")
        self.progressLabelRow.addWidget(self.progressPct)
        self.progressLayout.addLayout(self.progressLabelRow)
        self.pipelineProgress = QtWidgets.QProgressBar(parent=self.sidebarFrame)
        self.pipelineProgress.setMaximum(100)
        self.pipelineProgress.setProperty("value", 0)
        self.pipelineProgress.setTextVisible(False)
        self.pipelineProgress.setProperty("fixedHeight", 5)
        self.pipelineProgress.setObjectName("pipelineProgress")
        self.progressLayout.addWidget(self.pipelineProgress)
        self.sidebarLayout.addLayout(self.progressLayout)
        self.btnLayout = QtWidgets.QVBoxLayout()
        self.btnLayout.setContentsMargins(8, 6, 8, 10)
        self.btnLayout.setSpacing(6)
        self.btnLayout.setObjectName("btnLayout")
        self.runButton = QtWidgets.QPushButton(parent=self.sidebarFrame)
        self.runButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.runButton.setObjectName("runButton")
        self.btnLayout.addWidget(self.runButton)
        self.stopButton = QtWidgets.QPushButton(parent=self.sidebarFrame)
        self.stopButton.setEnabled(False)
        self.stopButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.stopButton.setObjectName("stopButton")
        self.btnLayout.addWidget(self.stopButton)
        self.sidebarLayout.addLayout(self.btnLayout)
        self.centerPanel = QtWidgets.QWidget(parent=self.mainSplitter)
        self.centerPanel.setObjectName("centerPanel")
        self.centerLayout = QtWidgets.QVBoxLayout(self.centerPanel)
        self.centerLayout.setContentsMargins(0, 0, 0, 0)
        self.centerLayout.setSpacing(0)
        self.centerLayout.setObjectName("centerLayout")
        self.logTabs = QtWidgets.QTabWidget(parent=self.centerPanel)
        self.logTabs.setDocumentMode(True)
        self.logTabs.setObjectName("logTabs")
        self.tabAllLogs = QtWidgets.QWidget()
        self.tabAllLogs.setObjectName("tabAllLogs")
        self.allLogsLayout = QtWidgets.QVBoxLayout(self.tabAllLogs)
        self.allLogsLayout.setContentsMargins(0, 0, 0, 0)
        self.allLogsLayout.setSpacing(0)
        self.allLogsLayout.setObjectName("allLogsLayout")
        self.logHeaderFrame = QtWidgets.QFrame(parent=self.tabAllLogs)
        self.logHeaderFrame.setStyleSheet("\n"
"QFrame#logHeaderFrame {\n"
"    background-color: #12151a;\n"
"    border-bottom: 1px solid #252c3a;\n"
"    min-height: 30px;\n"
"    max-height: 30px;\n"
"}\n"
"               ")
        self.logHeaderFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.logHeaderFrame.setObjectName("logHeaderFrame")
        self.logHeaderLayout = QtWidgets.QHBoxLayout(self.logHeaderFrame)
        self.logHeaderLayout.setContentsMargins(12, 0, 12, 0)
        self.logHeaderLayout.setSpacing(8)
        self.logHeaderLayout.setObjectName("logHeaderLayout")
        self.panelLabel = QtWidgets.QLabel(parent=self.logHeaderFrame)
        self.panelLabel.setObjectName("panelLabel")
        self.logHeaderLayout.addWidget(self.panelLabel)
        self.liveBadge = QtWidgets.QLabel(parent=self.logHeaderFrame)
        self.liveBadge.setObjectName("liveBadge")
        self.logHeaderLayout.addWidget(self.liveBadge)
        spacerItem1 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.logHeaderLayout.addItem(spacerItem1)
        self.launchButton = QtWidgets.QPushButton(parent=self.logHeaderFrame)
        self.launchButton.setEnabled(True)
        self.launchButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.launchButton.setStyleSheet("")
        self.launchButton.setObjectName("launchButton")
        self.logHeaderLayout.addWidget(self.launchButton)
        self.stopPrototypeButton = QtWidgets.QPushButton(parent=self.logHeaderFrame)
        self.stopPrototypeButton.setEnabled(False)
        self.stopPrototypeButton.setObjectName("stopPrototypeButton")
        self.logHeaderLayout.addWidget(self.stopPrototypeButton)
        self.allLogsLayout.addWidget(self.logHeaderFrame)
        self.logOutput = QtWidgets.QPlainTextEdit(parent=self.tabAllLogs)
        self.logOutput.setLineWrapMode(QtWidgets.QPlainTextEdit.LineWrapMode.WidgetWidth)
        self.logOutput.setReadOnly(True)
        self.logOutput.setObjectName("logOutput")
        self.allLogsLayout.addWidget(self.logOutput)
        self.logTabs.addTab(self.tabAllLogs, "")
        self.centerLayout.addWidget(self.logTabs)
        self.rightPanelFrame = QtWidgets.QFrame(parent=self.mainSplitter)
        self.rightPanelFrame.setMaximumSize(QtCore.QSize(350, 16777215))
        self.rightPanelFrame.setObjectName("rightPanelFrame")
        self.rightLayout = QtWidgets.QVBoxLayout(self.rightPanelFrame)
        self.rightLayout.setContentsMargins(0, 0, 0, 0)
        self.rightLayout.setSpacing(0)
        self.rightLayout.setObjectName("rightLayout")
        self.fileTreeHeaderFrame = QtWidgets.QFrame(parent=self.rightPanelFrame)
        self.fileTreeHeaderFrame.setStyleSheet("\n"
"QFrame#fileTreeHeaderFrame {\n"
"    background-color: #12151a;\n"
"    border-bottom: 1px solid #252c3a;\n"
"    min-height: 30px;\n"
"    max-height: 30px;\n"
"}\n"
"           ")
        self.fileTreeHeaderFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.fileTreeHeaderFrame.setObjectName("fileTreeHeaderFrame")
        self.fileTreeHeaderLayout = QtWidgets.QHBoxLayout(self.fileTreeHeaderFrame)
        self.fileTreeHeaderLayout.setContentsMargins(12, 0, 12, 0)
        self.fileTreeHeaderLayout.setObjectName("fileTreeHeaderLayout")
        self.fileTreeLabel = QtWidgets.QLabel(parent=self.fileTreeHeaderFrame)
        self.fileTreeLabel.setStyleSheet("color:#5a6a82; font-size:10px; font-weight:bold; letter-spacing:2px;")
        self.fileTreeLabel.setObjectName("fileTreeLabel")
        self.fileTreeHeaderLayout.addWidget(self.fileTreeLabel)
        spacerItem2 = QtWidgets.QSpacerItem(5, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.fileTreeHeaderLayout.addItem(spacerItem2)
        self.fileCountLabel = QtWidgets.QLabel(parent=self.fileTreeHeaderFrame)
        self.fileCountLabel.setStyleSheet("color:#5a6a82; font-size:10px;")
        self.fileCountLabel.setObjectName("fileCountLabel")
        self.fileTreeHeaderLayout.addWidget(self.fileCountLabel)
        self.rightLayout.addWidget(self.fileTreeHeaderFrame)
        self.fileTree = QtWidgets.QTreeWidget(parent=self.rightPanelFrame)
        self.fileTree.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.fileTree.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.NoSelection)
        self.fileTree.setIndentation(16)
        self.fileTree.setAnimated(True)
        self.fileTree.setHeaderHidden(True)
        self.fileTree.setObjectName("fileTree")
        self.rightLayout.addWidget(self.fileTree)
        self.dockerFrame = QtWidgets.QFrame(parent=self.rightPanelFrame)
        self.dockerFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.dockerFrame.setObjectName("dockerFrame")
        self.dockerLayout = QtWidgets.QVBoxLayout(self.dockerFrame)
        self.dockerLayout.setContentsMargins(0, 0, 0, 0)
        self.dockerLayout.setSpacing(0)
        self.dockerLayout.setObjectName("dockerLayout")
        self.dockerHeaderFrame = QtWidgets.QFrame(parent=self.dockerFrame)
        self.dockerHeaderFrame.setStyleSheet("\n"
"QFrame#dockerHeaderFrame {\n"
"    background-color: #12151a;\n"
"    border-bottom: 1px solid #252c3a;\n"
"    min-height: 30px;\n"
"    max-height: 30px;\n"
"}\n"
"              ")
        self.dockerHeaderFrame.setObjectName("dockerHeaderFrame")
        self.dockerHeaderLayout = QtWidgets.QHBoxLayout(self.dockerHeaderFrame)
        self.dockerHeaderLayout.setContentsMargins(12, 0, 12, 0)
        self.dockerHeaderLayout.setObjectName("dockerHeaderLayout")
        self.dockerTitleLabel = QtWidgets.QLabel(parent=self.dockerHeaderFrame)
        self.dockerTitleLabel.setStyleSheet("color:#5a6a82; font-size:10px; font-weight:bold; letter-spacing:2px;")
        self.dockerTitleLabel.setObjectName("dockerTitleLabel")
        self.dockerHeaderLayout.addWidget(self.dockerTitleLabel)
        spacerItem3 = QtWidgets.QSpacerItem(5, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.dockerHeaderLayout.addItem(spacerItem3)
        self.dockerLayout.addWidget(self.dockerHeaderFrame)
        self.dockerTable = QtWidgets.QTableWidget(parent=self.dockerFrame)
        self.dockerTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.dockerTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.dockerTable.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.dockerTable.setAlternatingRowColors(False)
        self.dockerTable.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.NoSelection)
        self.dockerTable.setShowGrid(False)
        self.dockerTable.setRowCount(3)
        self.dockerTable.setColumnCount(4)
        self.dockerTable.setObjectName("dockerTable")
        item = QtWidgets.QTableWidgetItem()
        self.dockerTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.dockerTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.dockerTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.dockerTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.dockerTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.dockerTable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.dockerTable.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.dockerTable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.dockerTable.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.dockerTable.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.dockerTable.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.dockerTable.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.dockerTable.setItem(2, 3, item)
        self.dockerTable.horizontalHeader().setVisible(True)
        self.dockerTable.horizontalHeader().setDefaultSectionSize(80)
        self.dockerTable.horizontalHeader().setStretchLastSection(True)
        self.dockerTable.verticalHeader().setVisible(False)
        self.dockerLayout.addWidget(self.dockerTable)
        self.rightLayout.addWidget(self.dockerFrame)
        self.rootLayout.addWidget(self.mainSplitter)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1216, 23))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(parent=self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuProject = QtWidgets.QMenu(parent=self.menuBar)
        self.menuProject.setObjectName("menuProject")
        self.menuSettings = QtWidgets.QMenu(parent=self.menuBar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menuBar)
        self.actionNewProject = QtGui.QAction(parent=MainWindow)
        self.actionNewProject.setObjectName("actionNewProject")
        self.actionOpenOutput = QtGui.QAction(parent=MainWindow)
        self.actionOpenOutput.setObjectName("actionOpenOutput")
        self.actionQuit = QtGui.QAction(parent=MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionClearOutput = QtGui.QAction(parent=MainWindow)
        self.actionClearOutput.setObjectName("actionClearOutput")
        self.actionSetOutputDir = QtGui.QAction(parent=MainWindow)
        self.actionSetOutputDir.setObjectName("actionSetOutputDir")
        self.actionConfigureAgents = QtGui.QAction(parent=MainWindow)
        self.actionConfigureAgents.setObjectName("actionConfigureAgents")
        self.actionResetPipeline = QtGui.QAction(parent=MainWindow)
        self.actionResetPipeline.setObjectName("actionResetPipeline")
        self.actionStartContainers = QtGui.QAction(parent=MainWindow)
        self.actionStartContainers.setObjectName("actionStartContainers")
        self.actionStopContainers = QtGui.QAction(parent=MainWindow)
        self.actionStopContainers.setObjectName("actionStopContainers")
        self.actionViewLogs = QtGui.QAction(parent=MainWindow)
        self.actionViewLogs.setObjectName("actionViewLogs")
        self.actionPreferences = QtGui.QAction(parent=MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionAbout = QtGui.QAction(parent=MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionNewProject)
        self.menuFile.addAction(self.actionOpenOutput)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuProject.addAction(self.actionClearOutput)
        self.menuProject.addAction(self.actionSetOutputDir)
        self.menuSettings.addAction(self.actionPreferences)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuProject.menuAction())
        self.menuBar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        self.logTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AutoPrototype"))
        self.promptLabel.setText(_translate("MainWindow", "PROMPT"))
        self.promptEdit.setPlaceholderText(_translate("MainWindow", "Describe the application you want to build..."))
        self.sectionLabel.setText(_translate("MainWindow", "AGENT PIPELINE"))
        __sortingEnabled = self.agentList.isSortingEnabled()
        self.agentList.setSortingEnabled(False)
        item = self.agentList.item(0)
        item.setText(_translate("MainWindow", "  Program Manager"))
        item.setToolTip(_translate("MainWindow", "Orchestrator — parses prompt and builds task graph"))
        item = self.agentList.item(1)
        item.setText(_translate("MainWindow", "  Frontend"))
        item.setToolTip(_translate("MainWindow", "UI / UX Agent — generates React/Vue/HTML components"))
        item = self.agentList.item(2)
        item.setText(_translate("MainWindow", "  Backend"))
        item.setToolTip(_translate("MainWindow", "API / Services Agent — generates server code and DB models"))
        item = self.agentList.item(3)
        item.setText(_translate("MainWindow", "  Exec Node"))
        item.setToolTip(_translate("MainWindow", "Execution Node — coordinates file writes and pipeline state"))
        item = self.agentList.item(4)
        item.setText(_translate("MainWindow", "  DevOps"))
        item.setToolTip(_translate("MainWindow", "Infra / Docker Agent — writes Dockerfiles and compose files"))
        item = self.agentList.item(5)
        item.setText(_translate("MainWindow", "  Debugger"))
        item.setToolTip(_translate("MainWindow", "Review / Fix Agent — validates output and corrects errors"))
        self.agentList.setSortingEnabled(__sortingEnabled)
        self.progressLabel.setText(_translate("MainWindow", "PIPELINE PROGRESS"))
        self.progressPct.setText(_translate("MainWindow", "0%"))
        self.runButton.setText(_translate("MainWindow", "▶   RUN PIPELINE"))
        self.stopButton.setText(_translate("MainWindow", "■   STOP"))
        self.panelLabel.setText(_translate("MainWindow", "LIVE OUTPUT"))
        self.liveBadge.setText(_translate("MainWindow", "● IDLE"))
        self.launchButton.setText(_translate("MainWindow", "▶ LAUNCH"))
        self.stopPrototypeButton.setText(_translate("MainWindow", "■ DESTROY"))
        self.logOutput.setPlaceholderText(_translate("MainWindow", "Pipeline output will appear here..."))
        self.logTabs.setTabText(self.logTabs.indexOf(self.tabAllLogs), _translate("MainWindow", "Agent Logs"))
        self.fileTreeLabel.setText(_translate("MainWindow", "OUTPUT DIRECTORY"))
        self.fileCountLabel.setText(_translate("MainWindow", "0 files"))
        self.fileTree.headerItem().setText(0, _translate("MainWindow", "File"))
        self.dockerTitleLabel.setText(_translate("MainWindow", "DOCKER CONTAINERS"))
        item = self.dockerTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "STATUS"))
        item = self.dockerTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "CONTAINER"))
        item = self.dockerTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "PORT"))
        item = self.dockerTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "STATE"))
        __sortingEnabled = self.dockerTable.isSortingEnabled()
        self.dockerTable.setSortingEnabled(False)
        item = self.dockerTable.item(0, 1)
        item.setText(_translate("MainWindow", "app_frontend"))
        item = self.dockerTable.item(0, 2)
        item.setText(_translate("MainWindow", ":3000"))
        item = self.dockerTable.item(0, 3)
        item.setText(_translate("MainWindow", "queued"))
        item = self.dockerTable.item(1, 1)
        item.setText(_translate("MainWindow", "app_backend"))
        item = self.dockerTable.item(1, 2)
        item.setText(_translate("MainWindow", ":8000"))
        item = self.dockerTable.item(1, 3)
        item.setText(_translate("MainWindow", "queued"))
        item = self.dockerTable.item(2, 1)
        item.setText(_translate("MainWindow", "app_postgres"))
        item = self.dockerTable.item(2, 2)
        item.setText(_translate("MainWindow", ":5432"))
        item = self.dockerTable.item(2, 3)
        item.setText(_translate("MainWindow", "queued"))
        self.dockerTable.setSortingEnabled(__sortingEnabled)
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuProject.setTitle(_translate("MainWindow", "Project"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.actionNewProject.setText(_translate("MainWindow", "New Project"))
        self.actionNewProject.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpenOutput.setText(_translate("MainWindow", "Open Output Folder"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionClearOutput.setText(_translate("MainWindow", "Clear Output"))
        self.actionSetOutputDir.setText(_translate("MainWindow", "Set Output Directory..."))
        self.actionConfigureAgents.setText(_translate("MainWindow", "Configure Agents..."))
        self.actionResetPipeline.setText(_translate("MainWindow", "Reset Pipeline"))
        self.actionStartContainers.setText(_translate("MainWindow", "Start All Containers"))
        self.actionStopContainers.setText(_translate("MainWindow", "Stop All Containers"))
        self.actionViewLogs.setText(_translate("MainWindow", "View Docker Logs"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences..."))
        self.actionPreferences.setShortcut(_translate("MainWindow", "Ctrl+,"))
        self.actionAbout.setText(_translate("MainWindow", "About ArchitectAI"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
