from core.graph import create_graph
from dotenv import load_dotenv

def run_autoprototype():
    load_dotenv()
    
    # Initialize the LangGraph app
    app = create_graph()
    
    # Define the starting state with a test idea
    initial_state = {
        "user_idea": """Build a calculator app""",
        "error_messages": [],
        "iteration_count": 0
    }
    
    print("--- Starting AutoPrototype Workflow ---")
    
    # We will keep track of the cumulative state here
    final_state = initial_state 
    
    # Open a debug file to write logs into so we don't flood the terminal
    with open("debug_log.txt", "w", encoding="utf-8") as log_file:
        log_file.write("=== AUTOPROTOTYPE DEBUG LOG ===\n")
        
        # Use .stream() instead of .invoke() to watch the workflow step-by-step
        for event in app.stream(initial_state):
            for node_name, state_update in event.items():
                print(f"Node Completed: {node_name}")
                
                # Log the exact outputs generated by this specific node
                log_file.write(f"\n\n{'='*50}\n")
                log_file.write(f"NODE: {node_name.upper()}\n")
                log_file.write(f"{'='*50}\n")
                
                for key, value in state_update.items():
                    log_file.write(f"\n--- {key.upper()} ---\n")
                    log_file.write(str(value) + "\n")
                    
                # Update our local state dictionary
                final_state.update(state_update)
    
    print("\nWorkflow Complete! Check 'debug_log.txt' for full inputs/outputs.")

    final_iterations = final_state.get("iteration_count", 0)
    unresolved_errors = final_state.get("error_messages", [])

    passed_first_try = (final_iterations == 0 and len(unresolved_errors) == 0)

    has_unresolved_bugs = len(unresolved_errors) > 0

    print("\n--- RUN METRICS ---")
    print(f"Passed First Try (Pass@1) : {passed_first_try}")
    print(f"Total Fix Iterations      : {final_iterations}")
    print(f"Unresolved Bugs Remain    : {has_unresolved_bugs}")

    print("\n--- FINAL ARCHITECTURE PLAN ---")
    print(final_state.get("architecture_plan", "No plan generated.")[:500] + "\n...(truncated)")

if __name__ == "__main__":
    run_autoprototype()