import re
from core.state import AutoPrototypeState
from langchain_anthropic import ChatAnthropic
from langchain_core.prompts import ChatPromptTemplate

def devops_agent_node(state: AutoPrototypeState) -> dict:
    print("DevOps Agent Active")

    llm = ChatAnthropic(model="claude-sonnet-4-6", temperature=0.1)

    data_code = state.get("data_code", "")
    bucket_needed = state.get("bucket_needed", False)
    db_readme     = _extract_section(data_code, "database/README.md")
    bucket_readme = _extract_section(data_code, "bucket/README.md") if bucket_needed else ""

    # --- NEW: Extract a dynamic list of all files generated by the Data Agent ---
    available_data_files = re.findall(r"###\s+(.*)", data_code)
    data_files_str = "\n".join(f"- ./{f.strip()}" for f in available_data_files) if available_data_files else "- None"
# --- NEW: Deterministic Schema Check ---
    # Search the ENTIRE backend codebase for migration tools, not just the first 1000 chars
    backend_full = state.get("backend_code", "").lower()
    backend_owns_schema = "flyway" in backend_full or "liquibase" in backend_full or "ddl-auto: update" in backend_full
    
    if backend_owns_schema:
        schema_instruction = "CRITICAL: The backend application owns the database schema (Flyway/Hibernate detected). DO NOT mount schema.sql or seed.sql into `/docker-entrypoint-initdb.d/`."
    else:
        schema_instruction = "CRITICAL: The backend does NOT handle migrations. You MUST mount the generated `schema.sql` and `seed.sql` into `/docker-entrypoint-initdb.d/` (prefix them with 1- and 2- to ensure order)."
    
    system_prompt = """
    You are a Principal DevOps Engineer.

    Your job is to provision the exact Docker Compose infrastructure required to run the generated prototype as a multi-service application.

    The system is NO LONGER allowed to run everything in one all-in-one container.
    You must use Docker Compose to orchestrate separate services.

    You must output infrastructure files using this exact multi-file format:

    ### docker-compose.yml
    ```yaml
    [CODE]
    ### backend/Dockerfile
    ```dockerfile
    [CODE]
    ```
    ### frontend/Dockerfile
    ```dockerfile
    [CODE]
    ```

    If the selected database is SQLite:

    DO NOT create database/Dockerfile
    DO NOT create a database service

    If bucket_needed is true:

    Add a MinIO service inside docker-compose.yml

    CRITICAL REQUIREMENTS:

    Use docker-compose.yml as the orchestrator.
    DO NOT create a single combined Dockerfile.
    Backend must run on port 8080.
    Frontend must run on port 5173.
    Backend must bind to 0.0.0.0:8080.
    Frontend must bind to 0.0.0.0:5173.

    Services must communicate using service names (NOT localhost).

    DATABASE LIFECYCLE RULES

    1. Persistent database volumes are for preserving runtime data across restarts.
    2. Database init scripts mounted into /docker-entrypoint-initdb.d/ only run on first initialization of a fresh data volume.
    3. Therefore, database init scripts must only be used when the database container fully owns schema creation and initial seed setup.
    4. If schema creation is handled by the backend application or migration layer, do NOT mount application seed files into /docker-entrypoint-initdb.d/.
    5. Never mix backend-owned schema creation with database-container init seeding for the same tables.
    6. For local prototype environments, choose exactly one strategy:
    - Strategy A: DB init owns schema + seed
    - Strategy B: backend/migrations own schema, and seeding happens after schema exists
    7. The selected strategy must be reflected consistently in docker-compose.yml, schema files, seed files, and backend startup behavior.
    8. If using a persistent named volume, the system must assume init scripts will not re-run automatically after first boot.
    9. If DB init seeding is used, the setup must be correct on the very first run with a fresh volume.
    10. If backend seeding is used, it must be idempotent and safe to run repeatedly.
    
    # --- NEW: Explicit instructions for mounting the dynamic data files ---
    11. IMPORTANT: If using Postgres/MySQL, you MUST mount the generated schema and seed files into the container's native initialization directory (e.g., `/docker-entrypoint-initdb.d/`).
    12. ONLY mount files that actually exist in the "Available Data Files" list provided below. Do not guess filenames.
    13. When mounting multiple SQL files, prefix the destination with numbers to ensure execution order (e.g., `/docker-entrypoint-initdb.d/1-schema.sql`, `/docker-entrypoint-initdb.d/2-seed.sql`).

    Example:

    backend connects to database via: database
    backend connects to minio via: minio

    Use environment variables for connection strings.

    Example:
    DATABASE_URL=postgresql://user:pass@database:5432/db

    If using Postgres/MySQL:
    Use official images unless required otherwise
    Provide required env vars
    Ensure persistence via volumes
    Ensure proper startup order using:
    depends_on
    or wait-for logic if necessary
    Do NOT rely on host machine tools inside containers.
    All services must be runnable via:
    docker compose up --build
    Output ONLY the required files in the exact format.
    Do NOT include explanations.
    """

    human_prompt = """Stack: {stack}

Architecture Plan:
{plan}

Backend Code (first 1000 chars):
{backend}

Frontend Code (first 1000 chars):
{frontend}

Available Data Files (Use these for volume mounts):
{data_files}

Database README:
{db_readme}

bucket_needed: {bucket_needed}
{bucket_section}
"""

    prompt = ChatPromptTemplate.from_messages([
        ("system", system_prompt),
        ("human", human_prompt)
    ])

    response = (prompt | llm).invoke({
        "stack":            state.get("selected_stack_name", "Unknown"),
        "selected_db_name": state.get("selected_db_name", "PostgreSQL"),
        "plan":             state.get("architecture_plan", ""),
        "backend":          state.get("backend_code", "")[:5000],
        "frontend":         state.get("frontend_code", "")[:1000],
        "data_files":       data_files_str, # <-- INJECT THE PARSED FILES HERE
        "db_readme":        db_readme or "(no database README found — check data_code)",
        "bucket_needed":    bucket_needed,
        "bucket_section":   f"Bucket README:\n{bucket_readme}" if bucket_needed else ""
    })

    content = response.content

    print("DevOps Agent Finished")

    if not content or "### docker-compose.yml" not in content:
        return {
            "infra_code": "",
            "execution_logs": "DEVOPS AGENT FAILED: output did not include docker-compose.yml"
        }

    return {
        "infra_code": content
    }


def _extract_section(data_code: str, filename: str) -> str:
    """Pull a specific file's content out of the data agent's multi-file output string."""
    if not data_code:
        return ""
    # Match ### database/README.md or ### bucket/README.md etc.
    escaped = re.escape(filename)
    match = re.search(rf"###\s+{escaped}\s+```\w*\n(.*?)```", data_code, re.DOTALL | re.IGNORECASE)
    return match.group(1).strip() if match else ""
